application: sotaagriculture
version: 123
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest
- name: MySQLdb
  version: "latest"
- name: setuptools
  version: latest

env_variables:
  CLOUDSQL_CONNECTION_NAME: sotaagriculture:us-central1:sigfoxdevice
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: k6vjyXC3L7dKT2DKrCTs
